apiVersion: v1
data:
    db-encryption-key: ENC[AES256_GCM,data:wVHMZYC7+hUAUN2LpQbvdpadRu8UtRGnwNLWkrtst/ZckcaSaC8qgxzxs2nbV/AZLp0gTIZXs2lmkJ/Ym2GW+0jWXVzBrHRL70grEUvGHa4i0XLyo5472A==,iv:C1InLBlg0GYih8ID/E9jRHPKmDA0I1zkSN7tZ/uGNTc=,tag:y/OTguwR6y8esSQgjgpeoQ==,type:str]
kind: Secret
metadata:
    name: db-encryption
    namespace: homarr
sops:
    age:
        - recipient: age15jjwhal370uylrdqnz6jfdefjm0l6k69ausa0rruyshr2utf6suq83g5x8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwM0MwMUlxbDh0clJCOWtT
            eFMxNlg1TjJ3WW55dkhBME1iOWNLdWxJZ0dJCldPSmt0ZVF4NURLR1JIWGZuTndO
            bTRpY1ZHSFJzOFM4YzNXNXBKc29EMzgKLS0tIFZqWEFNb1hGelFPNCtXKzJFSlRL
            dytWVWhGZ2VyOGlOaC9adEtqRndJdTgKFeLCBsXIiDRGTcRND/wjzEi+dsvp1n6a
            9oFYbrvrAJtZadtCW4A9YXwEAFMAe1WXRzYfAneM361PGQ1sj1rN5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T19:26:47Z"
    mac: ENC[AES256_GCM,data:zIIwpzO+7r3UvAD4eDzKpeJhmW0WnKUA7AKGHdEJMRnYu0EoOOvp69bW9CLk8Epz3PrH/2LdZIepBfcLdB1Sj00PfXWweId+XgCf9w7ySV2Mp4UWcyGkNWNQWnLXac/n1lFf8mFl21x82LBT23xXn8YP5O0/4lFLaS4IvhT/EoQ=,iv:8llSk4kRpXOIiUdwMVzcD9yW3RSnPeZ09kQmyPxJ05M=,tag:mE1THBQi+ArJQ+UlfO270Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
