apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:EQi4aNDZQ50+fUXRFYaTOWb+YXoQnsFMhr0ZWx09zJ6SU4sMpFe5Z2aDTv5jB/pr9q8xZ5ryiK4=,iv:fhaTQ7W6bPrGriUu6+wi8ZI+WweA3givyJdtB1zgqaY=,tag:2/JVfbi36Ks7M+EMR9vdvg==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age15jjwhal370uylrdqnz6jfdefjm0l6k69ausa0rruyshr2utf6suq83g5x8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cUNxYjNUeEV4ZjFDS09K
            UHlxSGh4aU04U2llQ0RrTkl1cHpnUDN3c2dJClJ4WEZ2clhmOGNMUlZtMHlwVGQ3
            K0YzbDN4RlB1T0VQLzlmUWptSTV0M2sKLS0tIEF4MjFCaVExdmhEMklDTlMwblVJ
            bTVld0xqNzlXZXg2YUhsalRCQjkvdkEK1liiqfj+GSWNJq9aPOmNsG7if7i5RBv8
            H5YjFUJfKB5HaULNxPTxu/W79X043BR04HsnxvOPipzrbCaD/tSf1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T07:51:13Z"
    mac: ENC[AES256_GCM,data:CeWggV9vfHjkt+wQBZ7/O+DjzvZSdcBRH9vX8MB99Qhhsvw2+BwmA+zoqORZBycb9q6nHFIcclwQ1+AXb2oFpECxIdEOAr6cCr2K1s6Z57YPSz4iVoEHo8GnnpL+EfNccXZoExlh8CD9BYLuePYZpdFxg1j3sG8cUqxWMaMtUsM=,iv:+a0kL1J0rOzIv3kb7xRP1th88JOWfPhrASpQykzjyto=,tag:mDbt2ZR5Yhl0M+G5Zgy2Sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
