apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: helm
spec:
  interval: 15m
  
  chart:
    spec:
      chart: traefik
      version: "39.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m0s

  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3

upgrade:
  remediation:
    retries: 3

  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
    cleanupOnFail: true

  values:
    deployment:
      replicas: 2
    ingressClass:
      enabled: false

    ports:
      web:
        port: 8000
        exposedPort: 80
      websecure:
        port: 8443
        exposedPort: 443
        tls:
          enabled: true

    service:
      type: LoadBalancer

    ingressRoute:
      dashboard:
        enabled: true
