kind: Deployment
metadata:
  name: cloudflared-homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-homarr
  template:
    metadata:
      labels:
        app: cloudflared-homarr
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - run
            - homarr
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-token
                  key: token
