apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-nginx-html-pvc
  namespace: blog 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
