apiVersion: v1
kind: Pod
metadata:
  name: blog-uploader
  namespace: blog
spec:
  containers:
    - name: uploader
      image: busybox
      command: ["sh", "-c", "sleep 1d"]
      volumeMounts:
        - name: blog-nginx-html-pvc
          mountPath: /data
  volumes:
    - name: blog-nginx-html-pvc
      persistentVolumeClaim:
        claimName: blog-nginx-html-pvc
