apiVersion: v1
data:
    tunnel-credentials: ENC[AES256_GCM,data:eSEZ1wG3kUjd/KUX7Y++Ppat5ZW73JDYZKUVj5sL3CBCph3ewBvGduTKQ5CVf0Ck3IAWVP0P+PFOh7aPNvZfRK5+4Zd/7XpYuJ0yxCky+vok5CzCUjbEFg==,iv:zmOmfx3BmM+ViFE6Litf1jjxU2OGFnRXrlUxJ6wxgz0=,tag:G2H4E18H8HEgtQpbY+1Y9Q==,type:str]
kind: Secret
metadata:
    name: audiobookshelf-tunnel-credentials
    namespace: audiobookshelf
sops:
    age:
        - recipient: age15jjwhal370uylrdqnz6jfdefjm0l6k69ausa0rruyshr2utf6suq83g5x8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOUNERXgybDVWL3dsNkFT
            bnVmaWZiNG4xRnpEbmZrUFNqWUVVME1SaURRCnhvK3duL1JlM1ltalBiZXcwdksz
            S3FvSW1GRlRwWllVY3E0cVFWL0RVMDAKLS0tIEdndkZuOWttNHNlMDdzVUhQNzRG
            TjVqQUJZL09Qc0srUmNVRm9TdG93UFEK2enMaE+gMeZEKurO2x6Dj2neaXgs6YXb
            vqKS14z3Ko6kXS/XoFlGOxyir/fgT2PPqx9h1jtm0WATZtaePA7lNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T17:26:04Z"
    mac: ENC[AES256_GCM,data:fZfZjUV9AO+9/Kv4own9hOs82+HHxDp1k6ZHkxux7m7qRhi+zfyAc3s2hWbx7Lw0p7aAtlvqrdxRKfnqTw7SvhX8bDn4MNpSJzJKX8CTd54jfXdixRmfNZVx0e1FAbIYFsgEmdmQnY0HwpJJzWLwj4XvsWICojKwO9KqQwztDE4=,iv:0CpX2wMAyuMXTi4Xm/3JZwf7W5uBg1hMd17eN0TMqfI=,tag:d80WA0duqxfbGrJyiVJp5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
