apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000 
        runAsUser: 1000 
        runAsGroup: 1000 

      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.33.2
          ports:
            - containerPort: 3005
              protocol: TCP
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap 

          volumeMounts:
            - name: data 
              mountPath: /data
              subPath: data 
            - name: data 
              mountPath: /config
              subPath: config 
            - name: data 
              mountPath: /metadata
              subPath: metadata 
            - name: data 
              mountPath: /audiobooks
              subPath: audiobooks 
            - name: data 
              mountPath: /podcasts
              subPath: podcasts 
     
      restartPolicy: Always

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-pvc
