apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:qly2pbaPjG7Tq1cAhZto1aCjAeBXXrihSPucUAUhTuyy3U9n6XgP2N8Uw/SGKNCO+lOMvPuCr0Sq/G1P3FEJ7Ik+Z0ZV38da/33A0ia0DjEPa4mvUPlCaOiG6IIyt/6p5yAT63qjpHruO3xzmHfX71djFDEapWlTYsRN1Mh9Oh7wZRTasH3ZgF3R4Mn7u4kXkmdTqxzN3vkIkpiaj70SnXabHK4PoVM/xVh13op+iSy4t+OJ0NDp+8nrJXOYUunPOTCpFoWatgqaDjP8yDq8D8c8nQv3dA2dLdJYT3/fas+xJGO3uJtEMTAT4xc=,iv:Gs1q/vTtbaGaJjRSm5ISO08+oEGqNGu7CVGCLluYHow=,tag:EHdxhq8oPg7XBZvlN5nUtw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age15jjwhal370uylrdqnz6jfdefjm0l6k69ausa0rruyshr2utf6suq83g5x8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWkpGTXZlUlE2WVo3Y3Jq
            aHZtRG0xOENvYS9nb0c1bUVrdzlPWk5xSWpjCnlXYlhBV0hlZmFDVkJMbnZUL2c1
            Kzk5TS93alZtZzR3WHpaS1NxMDhKUW8KLS0tIFZ2UGVTQnRGYlBrYkRUZzNwSXpK
            dERKeW5XRjBYeHRwTko3T01HdWxJYTAKoQazPJutGQLjHFYYerrJNcAeGi5D64DS
            /vGQypU91m+D40z6usBWJq5R4frqbB23ic+V7RC69fu0LPp57JIbAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T17:14:50Z"
    mac: ENC[AES256_GCM,data:AlzwAbJTkLr/ranUcCRnuPxA56D49DHray5T+sWo+d7jTQhZXbP4cF34kAcMfDVU0MdkEI7vzgba5tcZbbIbXABRf1Bm+NbQ6ucqXDRcBOvEcrH7wjzep5UMyzxSIjWByugmp4a1AUDIzri6fW8BWlsh6ilhaYbMF00D6/xS4mU=,iv:Yy/HaUbxI1PFzDa+PpzxW3lb5Ds3CEyR9uJ+3PiKFiE=,tag:kHOkJJaxsYCQgO5GxG7ZMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
