apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:DjmR8KjTDCQ=,iv:UP0UwUoQimJr87dwSN+AvADp++G5GOiWpqmZVdaMLrg=,tag:kExjgXqsyiAE2SI03ucTyA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:LlsAUJ7Z2+rnliFwCjnhdWaqLZI=,iv:xhnqEyiE8zmHl75u5qchsbyRWH9eZcR6cldGBckVIuk=,tag:xV36saGJsuYj5tIkKmHeCA==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age15jjwhal370uylrdqnz6jfdefjm0l6k69ausa0rruyshr2utf6suq83g5x8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UFVYam03QitUenltL1lB
            SHNUbEtoeXBBWW5ERllqNVU2U2w3dEkxWlVvCnV1emJOdzZRRkpMUUQ4OTgzM2ZZ
            Q0lwUVF1clpWMzFnR0JGY096bS9pTTgKLS0tIFBUbldlc2Q0eVpKTFJPYmhidWFS
            VFR6bndTcmlFWkgxMUVEdEt5bDJiM0EK078wjOXPaIHwKVurD7q3yXvZjEQMDcEr
            /19vm3KM5GTOJAbp53Eh/m0Hr4LcnRNGcUnSvU5rnyrR660XF3mGRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T15:03:02Z"
    mac: ENC[AES256_GCM,data:L69vH+KpmjMlvj5rn4nuPY9me+qkL9pUpQPvJZROa3WNE2PNuRik+W88j22w3EKUAfOmKVMZVvsVRKWrmQBIl6v7Xp597ZmF72Wrb7N9w5o5fpoh4QAay0PNOgjO1IbKt1Ky0bPDKoUYWn4W4cQ5DFIgxKZzIta/uCzuzqI6BIc=,iv:5sz7gWP3DXzivPEoh/N0kmYRJcUjBSofPTlADVMXXbA=,tag:f4urMVNFupzZxhUU65FRHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
