apiVersion: v1
data:
    tunnel-credentials-key: ENC[AES256_GCM,data:8e5VehBl3t8ccgyZXXG6a7CltPHpYO5cuDAgHJnGtOWKGpM5o91hAkc6KPouhao8X4RrZBtTiCHRN/cBEuCKBtunIabxpUtrzU1GfmyII8I4rQlDt8nTnw==,iv:MB8USG4wR2Jd2iyzkVptFb1vvctaQYrnCRlW0RJbF/o=,tag:eMW2KucxqpX8ArJ0ToTD1g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: mealie
sops:
    age:
        - recipient: age15jjwhal370uylrdqnz6jfdefjm0l6k69ausa0rruyshr2utf6suq83g5x8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJT2NHbnlObU9pSkx4OEtO
            VTVzQ1hkdGRNRHU3c1RPUi91NWYrRTFNT21VCmZZSUZ2NXBGdWgxdzVSTDM4bDlS
            OFEvNWVFSjhRMXYxMjNHR1kvZHUzTDAKLS0tIDZtWTdBaWxlRlkvTTNpMVZkNmdy
            NGdPUDQrNW94ZFp5anFpQko3Mi8wUW8KJHO9MNukBvz2s3LRCgXwK5zs1GoET3nw
            f0XU+i0hAOIQNnkPRKDdJaPmNNNbaKJOerVWrwgMGL5dTEgrXlx4UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T08:14:07Z"
    mac: ENC[AES256_GCM,data:MxCWNkoFoD1VoIlv6rOID8ltQHnS2bmMTkwvIXA+s5tc/m4hyvRZj6h+jJCVYKJLXhaxC/S2t5HdU8StZteEMQxDmvk+r6Z1lAg68SvEsxJu2RsJjhz5x6unlrZ09FoTCgOKrAcEelNMJ2tnLZ4W3DDzMHD51CR1axOqvzsqblE=,iv:2MAZuXKZ2X9IAU6NwkexGh0joIy4AEAibQ5xCCVxyOQ=,tag:wf2fe3CvQqJyrkk3l3i/Pw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
