apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: linkding
  namespace: linkding
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`lds.petrpoulik1492.com`)
      kind: Rule
      services:
        - name: linkding
          port: 9090
